### ISSUE TITLE
box design `mark_as_designed` should take box id param

### ISSUE THREAD

**Issue by abachman** [rubyforgood/voices-of-consent#133] opened 2019-07-28 14:30 UTC
needs to be more limited than just designed_by

**Comment by maebeale** [comment] 2019-10-06 05:44
Right now http://localhost:3000/box_design/new seems to be a design for the last box the user was assigned to, but it probably should require a box_id url param so we can mark the relevant box as designed (e.g. /boxes/:box_id/design)

**Comment by maebeale** [comment] 2019-10-10 22:45
Fixed via: https://github.com/rubyforgood/voices-of-consent/pull/278

**Closed as completed by maebeale** 2019-10-10 22:45 UTC
Labels: help wanted, Hacktoberfest
